"""
Alembic migration environment for Local AI Router benchmark persistence.

Alembic uses this module to:

1. Connect to PostgreSQL using the application's existing database
   configuration.
2. Discover benchmark ORM tables through BenchmarkBase.metadata.
3. Compare ORM metadata against the live PostgreSQL schema.
4. Execute version-controlled schema migrations.

Database credentials are deliberately not stored in Alembic configuration
files. The migration environment reuses the same environment-based settings
as the application.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection

from local_ai_router.persistence.benchmark.base import BenchmarkBase
from local_ai_router.persistence.database import (
    build_database_url,
    create_database_engine,
)


# Alembic provides this configuration object when a migration command runs.
alembic_config = context.config


# alembic.ini currently contains logging configuration generated by Alembic.
# If that file is later removed, this logging setup will need to be revisited.
if alembic_config.config_file_name is not None:
    fileConfig(alembic_config.config_file_name)


# This is the SQLAlchemy metadata Alembic will inspect during autogeneration.
#
# As benchmark ORM models are added, their tables will register themselves
# with BenchmarkBase.metadata.
target_metadata = BenchmarkBase.metadata


def run_migrations_offline() -> None:
    """
    Configure Alembic for offline SQL generation.

    Offline mode does not establish a live database connection. Instead,
    Alembic generates SQL statements that could be applied later.

    This is not our normal local-development workflow, but supporting it keeps
    the migration environment compatible with standard Alembic behavior.
    """

    database_url = build_database_url()

    context.configure(
        url=database_url.render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_with_connection(
    database_connection: Connection,
) -> None:
    """
    Configure and execute Alembic using an existing database connection.

    Args:
        database_connection:
            Active SQLAlchemy connection to the PostgreSQL database.
    """

    context.configure(
        connection=database_connection,
        target_metadata=target_metadata,
        include_schemas=True,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Execute migrations directly against PostgreSQL.

    The SQLAlchemy engine is created through the application's persistence
    configuration rather than from a password-containing URL stored in
    alembic.ini.
    """

    database_engine = create_database_engine()

    try:
        with database_engine.connect() as database_connection:
            run_migrations_with_connection(database_connection)
    finally:
        database_engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
