"""
Pydantic request and response schemas for the Local AI Router API.

Schemas define the structure of data that clients are allowed to send to the router
and the structureof data the router returns.

FastAPI uses ttese classes for several purposes:
    - validating incoming JSON,
    - converting JSON into python objects,
    - documenting the API automatically,
    - generating the OpenAPI specification,
    validating outgoing responses.

Kepping the API schemas seperate from routing and interface logic
prevents the HTTP interface from becoming tightly coupled to the internal implemenetation.
"""

from typing import Literal

from pydantic import BaseModel, Field


class RouteRequest(BaseModel):
    """
    Request body accepted by the /route endpoint.

    the /route endpoint evaluates routing policy without actually running an AI model.
    This makes it useful for testing and debugging router.

    Attributes:
        user_message (str):
            the users rrequest that should be classified.
            FFeld(min_length=1) prevets empty strings from being sent to the router.

        route_mode (Literal["auto", "fast", "reasoning"]):
            Controls how routing is performed.
            "auto" means the router decides.
            "fast" and "reasoning" force a particular route.
            Defaults to "auto" if not specified.

    """

    user_message: str = Field(min_length=1)
    route_mode: Literal["auto", "fast", "reasoning"] = "auto"


class RouteResponse(BaseModel):
    """
    Response returned by the /route endpoint.

    attributes:
        route_mode (Literal["fast", "reasoning"]):
            The route that the router has chosen to handle the request.
        thinking_enabled (bool):
            True if the chosen route will run the AI model with thinking/reasoning mode enabled.
        route_reason (str):
            Human-readable explanation of routing decision.
    """

    route_mode: Literal["fast", "reasoning"]
    thinking_enabled: bool
    route_reason: str


class ChatRequest(BaseModel):
    """
    Request body accepted by the /chat endpoint.

    Attributes:
        user_message (str): The users prompt that should be sent to the AI model.

        model_name (str): Optional explicit Ollama AI model name to use for inference.
            If not specified, the router uses DEFAULT_MODEL from config.py.
            This field exists primarily for testing and administrative use.
            Future client applications will normally allow the router itself to choose models.

        route_mode (Literal["auto", "fast", "reasoning"]):
            Controls how routing is performed.
            "auto" means the router decides.
            "fast" means force non-thinking inference.
            "reasoning" means force thinking inference.
            Defaults to "auto" if not specified.

    Note:
        The client no longer send a raw "thinking_enabled" Boolean.

        That is intentional. "think" is an Ollama/Qwen implementation detail, while "fast" and "reasoning" are
        capablitities exposed by our own router API
    """

    user_message: str = Field(min_length=1)
    model_name: str | None = None
    route_mode: Literal["auto", "fast", "reasoning"] = "auto"


class ChatResponse(BaseModel):
    """
    Response returned by the /chat endpoint

    Attributes:

        model_name (str):
            The Ollama model that actually genereated the response.

        route_mode(Literal["fast", "reasoning"]):
            Logical route selected by routing policy.

        thinking_enabled (bool):
            Whether thinking/reasoning mode was enabled for the inference request.

        route_reason (str):
            Explanation of why the router selected this route.

        response (str):
            Final texual response generated by the model.

        total_duration_ns (int):
            Total Ollama request duration in nanoseconds, when supplied by tthe backend.

        eval_count (int):
            Number of Output tokens evaluated/generated by Ollama

        eval_duration_ns (int):
            Time spent generating output tokens in nanoseconds.

    The performance fields are optional because the future inference backend
    may not expose exactly yht esame metrics as Ollama.
    """

    model_name: str
    route_mode: Literal["fast", "reasoning"]
    thinking_enabled: bool
    route_reason: str
    response: str
    total_duration_ns: int | None = None
    eval_count: int | None = None
    eval_duration_ns: int | None = None
